### ISSUE TITLE
Hi，mac下编译报错，可以帮忙看下原因吗

### ISSUE THREAD

**Issue by freewings85** [QiumingLu/skywalker#1]
已经按照readme编译了levelDB, voyager
-- Found Protobuf Compiler: /usr/local/bin/protoc
-- Found Protobuf (include: /usr/local/include, libraries: /usr/local/lib/libprotobuf.dylib)
-- Found LevelDB (include: /usr/local/include, library: /usr/local/lib/libleveldb.dylib)
CMake Error at /usr/local/Cellar/cmake/3.11.2/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:137 (message):
  Could NOT find Voyager (missing: VOYAGER_LIBRARY)

/usr/local/lib下voyager相关的文件如下:
$ ls | grep voyager
libvoyager_core.1.6.dylib
libvoyager_core.1.dylib
libvoyager_core.a
libvoyager_core.dylib
libvoyager_http.1.6.dylib
libvoyager_http.1.dylib
libvoyager_http.a
libvoyager_http.dylib
libvoyager_port.1.6.dylib
libvoyager_port.1.dylib
libvoyager_port.a
libvoyager_port.dylib
libvoyager_rpc.1.6.dylib
libvoyager_rpc.1.dylib
libvoyager_rpc.a
libvoyager_rpc.dylib
libvoyager_util.1.6.dylib
libvoyager_util.1.dylib
libvoyager_util.a
libvoyager_util.dylib

**Comment by QiumingLu** [comment]
你看下skywalker的编译流程，动态库是需要安装到系统的目录下才可以的，你现在是编译成功，但是并没有把voyager安装过去

**Comment by freewings85** [comment]
没有安装是什么意思？已经按照你的步骤执行过make install了，都是默认配置，没有改动，/usr/local/lib里面也有不少libvoyager*的库文件

**Comment by freewings85** [comment]
好像是voyager版本的问题，我试试最新的

**Comment by freewings85** [comment]
编译通过了，之前vogaer用到项目里面链接的分支，用最新的版本就可以了=。=
